/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ddpg;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tasca
 */
public class EditarProntuario extends javax.swing.JFrame {

    /**
     * Creates new form EditarProntuario
     */
    public EditarProntuario() {
        initComponents();
        listarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JTextField();
        Sair = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        Remedios = new javax.swing.JTextField();
        Retorno = new javax.swing.JTextField();
        ID_Paciente = new javax.swing.JTextField();
        Diagnostico = new javax.swing.JTextField();
        Carregar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        CriarProntuario = new javax.swing.JButton();
        Pacientes = new javax.swing.JButton();
        Prontuario = new javax.swing.JButton();
        ID_Consulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaProntuario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 170, -1));

        Sair.setContentAreaFilled(false);
        Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 250, 50));

        jTextField3.setText("jTextField1");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 170, -1));
        getContentPane().add(Remedios, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 170, -1));
        getContentPane().add(Retorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 170, -1));
        getContentPane().add(ID_Paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 170, -1));
        getContentPane().add(Diagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 170, -1));

        Carregar.setContentAreaFilled(false);
        Carregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarActionPerformed(evt);
            }
        });
        getContentPane().add(Carregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, 100, 30));

        Excluir.setContentAreaFilled(false);
        Excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, 100, 30));

        Editar.setContentAreaFilled(false);
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        getContentPane().add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 630, 100, 30));

        Limpar.setContentAreaFilled(false);
        Limpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        getContentPane().add(Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, 100, 30));

        CriarProntuario.setContentAreaFilled(false);
        CriarProntuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CriarProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarProntuarioActionPerformed(evt);
            }
        });
        getContentPane().add(CriarProntuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, 130, 50));

        Pacientes.setContentAreaFilled(false);
        Pacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacientesActionPerformed(evt);
            }
        });
        getContentPane().add(Pacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 170, 40));

        Prontuario.setContentAreaFilled(false);
        Prontuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Prontuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProntuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Prontuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 170, 40));

        ID_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_ConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(ID_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 170, -1));

        TabelaProntuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Prontuário", "ID Consulta", "Diagnóstico", "Remedios", "Retorno", "ID Paciente"
            }
        ));
        jScrollPane1.setViewportView(TabelaProntuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 740, 350));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipos/8.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ID_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_ConsultaActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void ProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProntuarioActionPerformed
        // TODO add your handling code here:
        new EditarProntuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProntuarioActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void PacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacientesActionPerformed
        // TODO add your handling code here:
        new EditarPacientes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PacientesActionPerformed

    private void CarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarActionPerformed
        // TODO add your handling code here:
        CarregarCampos();
        
    }//GEN-LAST:event_CarregarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
        ExcluirProntuario();
        listarValores();
        LimparCampos();
        
    }//GEN-LAST:event_ExcluirActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        AlterarProntuarios();
        listarValores();
        LimparCampos();
    }//GEN-LAST:event_EditarActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // TODO add your handling code here:
        LimparCampos();
    }//GEN-LAST:event_LimparActionPerformed

    private void CriarProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarProntuarioActionPerformed
        // TODO add your handling code here:
        new CadastroProntuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CriarProntuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarProntuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carregar;
    private javax.swing.JButton CriarProntuario;
    private javax.swing.JTextField Diagnostico;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField ID_Consulta;
    private javax.swing.JTextField ID_Paciente;
    private javax.swing.JButton Limpar;
    private javax.swing.JButton Pacientes;
    private javax.swing.JButton Prontuario;
    private javax.swing.JTextField Remedios;
    private javax.swing.JTextField Retorno;
    private javax.swing.JButton Sair;
    private javax.swing.JTable TabelaProntuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
private void listarValores() { //Declaração do método listarValores(). Esse método é provavelmente parte de uma classe e é responsável por preencher uma tabela ou lista com valores obtidos de algum lugar, como um banco de dados.
        try {
            ProntuarioDAO objProntuarioDAO = new ProntuarioDAO();
            DefaultTableModel model = (DefaultTableModel) TabelaProntuario.getModel();
            model.setNumRows(0);

            ArrayList<Prontuario> lista = objProntuarioDAO.PesquisarProntuario();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_Prontuario(),
                     lista.get(num).getId_Consulta(),
                   
                   lista.get(num).getDiagnostico(),
                   
                    lista.get(num).getRemedios_Prescritos(),
                     lista.get(num).getRetorno(),
                     lista.get(num).getId_Paciente(),
                  
                });

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Valores :" + erro);
        }
    }

  private void CarregarCampos() {
/*
        Esse método é responsável por carregar os campos de texto da interface com os valores selecionados na tabela. Ele faz o seguinte:

Obtém o índice da linha selecionada na tabela através do método getSelectedRow().
Através do modelo da tabela (TabelaProntuarios.getModel()), obtém os valores correspondentes da linha selecionada.
Define os valores obtidos nos campos de texto Id, User, Telefone e Email.
 */        
        int setar = TabelaProntuario.getSelectedRow();

        ID.setText(TabelaProntuario.getModel().getValueAt(setar, 0).toString());
        
           ID_Paciente.setText(TabelaProntuario.getModel().getValueAt(setar, 1 ).toString());
         
        Diagnostico.setText(TabelaProntuario.getModel().getValueAt(setar, 2).toString());
        Retorno.setText(TabelaProntuario.getModel().getValueAt(setar, 3).toString());
        Remedios.setText(TabelaProntuario.getModel().getValueAt(setar, 4).toString());
        ID_Consulta.setText(TabelaProntuario.getModel().getValueAt(setar, 5).toString());
     
    }

    private void LimparCampos() {
/*
        Esse método é responsável por limpar os campos de texto da interface. Ele simplesmente define o texto vazio para os campos Id, User, Telefone e Email.
 */        
        ID.setText("");
        
        ID_Paciente.setText("");
        
        Diagnostico.setText("");
        Retorno.setText("");
        Remedios.setText("");
        ID_Consulta.setText("");
    }

    private void AlterarProntuarios() {
 /*
 Esse método é responsável por alterar as informações de um usuário. Ele faz o seguinte:

Obtém os valores dos campos Id, User, Telefone e Email.
Cria uma instância da classe Prontuarios e define os valores obtidos nos respectivos atributos.
Cria uma instância da classe ProntuariosDAO.
Chama o método AlterarProntuarios() da classe ProntuariosDAO, passando o objeto objProntuarios como argumento para realizar a alteração no banco de dados.   
 */        

         int id_prontuario;
        int id_paciente;
        String diagnostico;
        String retorno;
        String remedios_prescritos;
        int id_consulta;
        
        
        

        id_prontuario = Integer.parseInt(ID.getText());
        
         id_paciente = Integer.parseInt(ID_Paciente.getText());
          retorno = Retorno.getText();
        remedios_prescritos = Remedios.getText();
        id_consulta = Integer.parseInt(ID_Consulta.getText());
        diagnostico = Diagnostico.getText();
        
        
        Prontuario objProntuarios = new Prontuario();
        objProntuarios.setId_Prontuario(id_prontuario);
        objProntuarios.setDiagnostico(diagnostico);
         objProntuarios.setId_Paciente(id_paciente);
        objProntuarios.setRetorno(retorno);
        objProntuarios.setRemedios_Prescritos(remedios_prescritos);
        objProntuarios.setId_Consulta(id_consulta);

        ProntuarioDAO objProntuariosDAO = new ProntuarioDAO();
        objProntuariosDAO.AlterarProntuario(objProntuarios);

    }

    private void ExcluirProntuario() {
 /*
 Esse método é responsável por excluir um usuário. Ele faz o seguinte:

Obtém o valor do campo Id e converte para o tipo inteiro.
Cria uma instância da classe Prontuario e define o valor do ID obtido no atributo id.
Cria uma instância da classe ProntuarioDAO.
Chama o método ExcluirProntuario() da classe ProntuarioDAO, passando o objeto objProntuario como argumento para realizar a exclusão no banco de dados.   
 */            
        int id = 0;

        id = Integer.parseInt(ID.getText());

        Prontuario objProntuario = new Prontuario();
        objProntuario.setId_Prontuario(id);

        ProntuarioDAO objProntuarioDAO = new ProntuarioDAO();
        objProntuarioDAO.ExcluirProntuario(objProntuario);
    }


}
