/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ddpg;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 62127512022.3
 */
public class EditarConsultas extends javax.swing.JFrame {

    /**
     * Creates new form EditarConsultas
     */
    public EditarConsultas() {
        initComponents();
        listarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID_Paciente = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        Horario = new javax.swing.JTextField();
        Data_Consulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaConsultas = new javax.swing.JTable();
        Limpar = new javax.swing.JButton();
        Carregar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        ConfiguracoesPaciente = new javax.swing.JButton();
        Gerenciamento = new javax.swing.JButton();
        AgendarConsulta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ID_Paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 180, -1));
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 180, -1));
        getContentPane().add(Horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 180, -1));

        Data_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_ConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(Data_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 180, -1));

        TabelaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Consulta", "ID Paciente", "Horario", "Data"
            }
        ));
        jScrollPane1.setViewportView(TabelaConsultas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 740, 320));

        Limpar.setContentAreaFilled(false);
        Limpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        getContentPane().add(Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, 100, 30));

        Carregar.setContentAreaFilled(false);
        Carregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarActionPerformed(evt);
            }
        });
        getContentPane().add(Carregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 90, 30));

        Excluir.setContentAreaFilled(false);
        Excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, 100, 30));

        Editar.setContentAreaFilled(false);
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        getContentPane().add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 630, 100, 30));

        Sair.setContentAreaFilled(false);
        Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 623, 260, 50));

        ConfiguracoesPaciente.setContentAreaFilled(false);
        ConfiguracoesPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConfiguracoesPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracoesPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(ConfiguracoesPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 170, 40));

        Gerenciamento.setContentAreaFilled(false);
        Gerenciamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciamentoActionPerformed(evt);
            }
        });
        getContentPane().add(Gerenciamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 170, 50));

        AgendarConsulta.setContentAreaFilled(false);
        AgendarConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendarConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(AgendarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipos/Editar Consultas.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1001, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Data_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Data_ConsultaActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void ConfiguracoesPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracoesPacienteActionPerformed
        // TODO add your handling code here:
        new EditarPacientesSecretaria().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConfiguracoesPacienteActionPerformed

    private void GerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciamentoActionPerformed
        // TODO add your handling code here:
        new EditarConsultas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GerenciamentoActionPerformed

    private void CarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarActionPerformed
        // TODO add your handling code here:
        CarregarCampos();
    }//GEN-LAST:event_CarregarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
        ExcluirConsultas();
        listarValores();
        LimparCampos();
    }//GEN-LAST:event_ExcluirActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        AlterarConsultas();
        listarValores();
        LimparCampos();
    }//GEN-LAST:event_EditarActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // TODO add your handling code here: 
        LimparCampos();
    }//GEN-LAST:event_LimparActionPerformed

    private void AgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendarConsultaActionPerformed
        // TODO add your handling code here:
        new CadastroConsulta().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_AgendarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgendarConsulta;
    private javax.swing.JButton Carregar;
    private javax.swing.JButton ConfiguracoesPaciente;
    private javax.swing.JTextField Data_Consulta;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Gerenciamento;
    private javax.swing.JTextField Horario;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField ID_Paciente;
    private javax.swing.JButton Limpar;
    private javax.swing.JButton Sair;
    private javax.swing.JTable TabelaConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
private void listarValores() { //Declaração do método listarValores(). Esse método é provavelmente parte de uma classe e é responsável por preencher uma tabela ou lista com valores obtidos de algum lugar, como um banco de dados.
        try {
            ConsultasDAO objConsultasDAO = new ConsultasDAO();
            DefaultTableModel model = (DefaultTableModel) TabelaConsultas.getModel();
            model.setNumRows(0);

            ArrayList<Consultas> lista = objConsultasDAO.PesquisarConsulta();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_Consulta(),
                     lista.get(num).getId_Paciente(),
                   lista.get(num).getHorario(),
                    lista.get(num).getData_Consulta()
                });

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Valores :" + erro);
        }
    }

  private void CarregarCampos() {
/*
        Esse método é responsável por carregar os campos de texto da interface com os valores selecionados na tabela. Ele faz o seguinte:

Obtém o índice da linha selecionada na tabela através do método getSelectedRow().
Através do modelo da tabela (TabelaConsultass.getModel()), obtém os valores correspondentes da linha selecionada.
Define os valores obtidos nos campos de texto Id, User, Telefone e Email.
 */        
        int setar = TabelaConsultas.getSelectedRow();

        ID.setText(TabelaConsultas.getModel().getValueAt(setar, 0).toString());
        
         ID_Paciente.setText(TabelaConsultas.getModel().getValueAt(setar, 1 ).toString());
         
        Horario.setText(TabelaConsultas.getModel().getValueAt(setar, 2).toString());
        Data_Consulta.setText(TabelaConsultas.getModel().getValueAt(setar, 3).toString());
        
     
    }

    private void LimparCampos() {
/*
        Esse método é responsável por limpar os campos de texto da interface. Ele simplesmente define o texto vazio para os campos Id, User, Telefone e Email.
 */        
        ID.setText("");
        
        ID_Paciente.setText("");
        
        Horario.setText("");
        Data_Consulta.setText("");
    
    }

    private void AlterarConsultas() {
 /*
 Esse método é responsável por alterar as informações de um usuário. Ele faz o seguinte:

Obtém os valores dos campos Id, User, Telefone e Email.
Cria uma instância da classe Consultass e define os valores obtidos nos respectivos atributos.
Cria uma instância da classe ConsultassDAO.
Chama o método AlterarConsultass() da classe ConsultassDAO, passando o objeto objConsultass como argumento para realizar a alteração no banco de dados.   
 */        

        int id_consulta;
        int id_paciente;
        String horario;
        String data_consulta;
        
        
        
        
        
        

        id_consulta = Integer.parseInt(ID.getText());
      id_paciente = Integer.parseInt(ID_Paciente.getText());
          horario = Horario.getText();
        data_consulta = Data_Consulta.getText();
      
        
  
        
        Consultas objConsultass = new Consultas();
        objConsultass.setId_Consulta(id_consulta);
       
         objConsultass.setId_Paciente(id_paciente);
        objConsultass.setHorario(horario);
        objConsultass.setData_Consulta(data_consulta);
        

        ConsultasDAO objConsultassDAO = new ConsultasDAO();
        objConsultassDAO.AlterarConsultas(objConsultass);

    }

    private void ExcluirConsultas() {
 /*
 Esse método é responsável por excluir um usuário. Ele faz o seguinte:

Obtém o valor do campo Id e converte para o tipo inteiro.
Cria uma instância da classe Consultas e define o valor do ID obtido no atributo id.
Cria uma instância da classe ConsultasDAO.
Chama o método ExcluirConsultas() da classe ConsultasDAO, passando o objeto objConsultas como argumento para realizar a exclusão no banco de dados.   
 */            
        int id = 0;

        id = Integer.parseInt(ID.getText());

        Consultas objConsultas = new Consultas();
        objConsultas.setId_Consulta(id);

        ConsultasDAO objConsultasDAO = new ConsultasDAO();
        objConsultasDAO.ExcluirConsultas(objConsultas);
    }




}
