/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ddpg;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author tasca
 */
public class Login extends javax.swing.JFrame {
public static String role = "NULL";
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
boolean login = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JTextField();
        Senha = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 350, 30));
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 350, 30));

        Login.setContentAreaFilled(false);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 330, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipos/1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 998, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
          String us = Nome.getText();
        String ps = Senha.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/ddpg", "root", "");
            Statement st = (Statement) conn.createStatement();
            String sql = "SELECT * FROM funcionario";
            ResultSet rs = st.executeQuery(sql);
            String funcao = ""; // Initialize the funcao variable outside the loop

            while (rs.next()) {
                String username = rs.getString("Nome");
                String password = rs.getString("Senha");

                if (us.equals(username) && ps.equals(password)) {
                   String query = "SELECT Cargo FROM funcionario WHERE Nome = '" + username + "' AND Senha = '" + password + "'";

                    ResultSet result = st.executeQuery(query);

                    if (result.next()) {
                        funcao = result.getString("Cargo");
                        String upperfuncao = funcao.toUpperCase();

                        if (upperfuncao.equals("ORTOPEDISTA") || upperfuncao.equals("ORTO") || upperfuncao.equals("ADMINISTRADOR") || upperfuncao.equals("ORTOPED")) {
                            JOptionPane.showMessageDialog(this, "Bem-vindo, " + username);
                            
                            new EditarProntuario().setVisible(true);
                            
                            this.dispose();
                        } else if (upperfuncao.equals("SECRETARIA") || upperfuncao.equals("SECRET") || upperfuncao.equals("SECRE") ) {
                            JOptionPane.showMessageDialog(this, "Bem-vindo, " + username);
                          
                            new EditarConsultas().setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Login falho, função inválida");
                        }
                    }

                    result.close();
                    login = true; // Set the login variable to true if login is successful
                    break;
                }
            }

            rs.close();
            st.close();
            conn.close();

            if (!login) {
                JOptionPane.showMessageDialog(null, "Usuário ou senha incorreta!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o Banco de dados!");
        }
    }//GEN-LAST:event_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    /*
    
    */
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JTextField Nome;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
